### ISSUE TITLE
--capacity not working

### ISSUE THREAD

**Issue by eschek87** [equelin/vsanmetrics#2]
Traceback (most recent call last):
  File "/opt/vsanmetrics/vsanmetrics.py", line 494, in <module>
    main()
  File "/opt/vsanmetrics/vsanmetrics.py", line 361, in main
    if spaceReport.efficientCapacity:
AttributeError: 'vim.cluster.VsanSpaceUsage' object has no attribute 'efficientCapacity'

**Comment by eschek87** [comment]
I did not used the latest version of the sdk (I used 6.6 instead of 6.7)
