### ISSUE TITLE
Error if one host from cluster is down

### ISSUE THREAD

**Issue by eschek87** [equelin/vsanmetrics#4]
If I ran the command to query the cluster for e.g. performance metrics and one host of the cluster is not available, then the whole command fails:

python /opt/vsanmetrics/vsanmetrics.py -s <vc> -u <user> -p <password>-c <cluster> --performance
Traceback (most recent call last):
  File "/opt/vsanmetrics/vsanmetrics.py", line 584, in <module>
    main()
  File "/opt/vsanmetrics/vsanmetrics.py", line 466, in main
    uuid, disks = getInformations(content, cluster_obj)
  File "/opt/vsanmetrics/vsanmetrics.py", line 108, in getInformations
    diskAll = host.configManager.vsanSystem.QueryDisksForVsan()
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.HostNotConnected: (vmodl.fault.HostNotConnected) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Unable to communicate with the remote host, since it is disconnected.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

**Comment by equelin** [comment]
Hello @eschek87,

Thanks for your feedback. I just checked by myself and you are right. I'll try to produce a patch this week.

**Comment by equelin** [comment]
Hello @eschek87 ,

The new release of **vsanmetrics** will hopefully correct this issue. There is a cache system that can be use to improve the global performances and to help if a host is down.

https://github.com/equelin/vsanmetrics/releases/tag/0.5.0

Please provide feedback if you have time to test the script !

**Comment by eschek87** [comment]
Hi,
yes it works! Thanks!
